#+TITLE: 每周周报
#+TAGS: work(w) home(h)
#+TAGS: idea(i) inspiration(p)

* <2014-08-10 Sun>

** 																	   :work:
周一上了一天的课程，入职3年以上的员工们给我们讲了一些关于新人进入tencent的一些建议，主要在工作、生活以及交际上，更多的是如何做好沟通和如何规划好自己的职业发展道路。 *沟通* 是一门学问，这么多年走来，一直都被沟通困扰，不过最近总结出了一条， *站在别人的角度考虑问题，以平常心对待一切* 。这可以使得沟通变得更加的简单和直接。

剩余的工作日主要在写异步的spp，效率感觉挺一般的，完成的情况也不是特别满意。自己近段时间一直在考虑如何更加高效的去做一件事情，  我相信无论是读书还是工作，每件事的内在都存在的一定的统一性，如何已我现有的经验和知识体系，去更加高效的完成任务和解决问题是我应该探索的。其实编程对我来说并不是一件非常容易的事情，毕竟是半路杀出来的，没有经过系统的学习和训练，不过幸运的是，自己对编程还是有兴趣的。人嘛，总要对自己的有清晰的认识，虽然自信是必须的，但现实情况必须要很好的把握，不要不切合实际的去追求，那会死得很惨的。所以，很多时候还是要 *静下心* 来平平静静的做一些事情，一点一滴的积累。

本周算是入职一个月了，peter还特地找我聊了聊，其实发现聊的时候主要说话的还是我，哎，还是担心冷场，所以自己哗啦啦的说个没完，不过感觉自己现在还是挺明白自己的目标的： *强化自己的专业知识，丰富自己的业余视野* 。总体来说这一个月过得还挺不错的，和组里的同事们比较熟，所以也能更加平等的交流，比实习的时候好多了，那时候更多的还是太过于小看自己了。其实，每次交流的时候， *人与人之间的平等性* 对于正常的交流很重要，每次不敢或者不能好好交流，就是要么太高看自己了，要么就是太高看别人了，原因无非这几种。

** 																	   :home:
这几个周末过的其实挺一般的，主要还是感觉心态还是不太好，没有一颗平常心。不过这几个周末，跑步、看书的生活其实挺享受的。或许是因为太着急于钱的事儿了，这真是急不来的事情，准备好自己，该来的总会来的，所以 prepare myself！

** 																	   :idea:
1) 为啥安踏不做智能硬件呢？类似NIKE+这样的东西，屌丝的中国就需要屌丝的NIKE+啊。
