#+TITLE: 每周周报
#+TAGS: work(w) home(h)
#+TAGS: idea(i) inspiration(p)

* 2014-09-15 Mon
** 																	   :work:
不知不觉好久没有写周记了，持之以恒真的是这个世界上最难的事情之一。上上周去了厦门，和范大小姐度过了一个惬意而舒适的中秋，这样慵懒和没有目的性的生活是人这一生中不可或缺的调味剂。铭记每一次这样的经历，记住生活的本质，探索生命的意义。上周因为中秋放假只有4天的工作时间，感觉中秋回来以后状态不佳，事情进展都比较缓慢，todo list越来越长，进而成就感也就越来越低。上周邮件提示自己已经进入公司已经2个月了，时间过得真快，以这样的速度，不知不觉就已经一年过去了，不知道自己一年能成长多少，心中惶惶。

最近发现上班时候属于自己的时间越来越少，忙于应付各种各样的问题，缺少了自我学习的时间，越来越紧的schedule，有点让自己喘不过气来。仔细想想，发现自己其实自从入职以来一直在培养自己的工作习惯，如何高效地完成工作，我相信在哪一行都是一样的，而这需要经验，需要实践，需要尝试。记得刚进公司的时候培训有谈到如何安排自己的工作优先级的问题，现在自己正在面临这样的困境。认证空间刚接手，太长时间没有维护，有很多的小bug，所以经常会在专心做一件事情的时候被别的事情打断。现在，高效的完成工作成了我遇到的第一个职业挑战。自己的工作习惯只能自己慢慢培养:
1) 尝试尽量以固定间隔去做查看邮件、查看rtx这样的事情，尽量以集中的时间去处理一个事情，毕其功于一役。
2) 琐碎的小事，尽量先做掉，一则可以提升自己的成就感和效率感，另外，其实处理完所有的小事，会让自己轻松很多。
3) 学会给事情排优先级、什么样的事情应该先做，什么样的事情应该后做，自己应该有个准确的判断，一个人的处理能力都是有限的，懂得取舍。
4) 每天尽量给自己学习的时间，忙于琐事会让自己失去方向，忘记初衷，牢记自己的目标是什么，不要一味往前冲，认清自己的方向。

公司培训的时候有同事分享说， *自己搞过的每个项目都得负责任* 。责任对于一个职场人来说应该是最基础的，不要太在意眼前的成败，要有一些担当。上周有个挺大的事故，在操作crontab的时候不小心输入了crontab -r，该命令删除了当前用户的crontab。因为没有备份（为啥这么大的公司crontab竟然没有备份），所以给机器上的服务造成了影响，当天花了半天的时间从系统的执行记录message中恢复了crontab。自己的错误就要自己承担，不要尝试着去隐藏什么，尤其是你还是新手的时候，所有的错误都可以以最小的代价被尝试，以后你就会记住这样的错误坚决不能再犯。如果尝试去隐藏，那么只会让事情一团糟。
** 																	   :home:
* 2014-08-25 Mon
** 																	   :work:
上周因为玩LOL，搞的写周报的心情都木有了，所以只能把LOL卸载了，真是玩物丧志啊！今天都周一了，要是不动笔写点什么，那可能这周就空白了，那以后可能就会越来越多的空白，万事开头难，一定要坚持下去，好啦，废话唠叨够了。
上周任务其实是没有按时完成的，但今天周一发现效率挺高的，很多问题都迎刃而解了，所以本周一一下子就把进度追上了。本来上周想加个班把事情搞定的，其实这不是我的风格，我只会在上班的时候把多出来的时间用来做自己的事情，绝对不会把自己的时间用来做被安排的任务。所以还是坚持自己的选择， *效率为王* ，周末加班什么能避免就尽量避免吧。最近发现自己有点进入状态了，很多业务上手也很快，主要是胆子不像以前那么小了，现在更加敢于去问，去了解一些东西，这对我来说是好事情，但要注意其实每个人都有自己的安排，你不能太过于平常的去打扰别人的工作，而且，在得到别人帮助或者请求别人帮助时，必要的感谢还是要的，这是最基本的礼仪。上周发现自己还是有抱怨的情绪，这本来就是我的一大问题，团队中的人各式各样，要学会面对各种各样的队友，不要去评价一个队友，做你自己应该做的事情，能帮助别人的地方就帮助别人，别人能帮助你就很不错了，不要要求更多，正所谓 *对己严格要求，对人宽厚仁慈* 。还有就是不要轻易的表达自己的负面情绪，有很多时候简单的陈述事实就可以了，不要对这件事的本身进行带有评价性的描述，这样很不好，自己也很不喜欢。

** 																	   :home:
上周因为工作状态不佳，然后间接影响到了生活状态，导致和驴盆盆的关系有危机。生活和工作是每个人都必须面对的难题，对于我来说更加如此，工作毫无疑问在我的生命中占据了很大一部分，但其实生活对我来说应该成为更加重要的部分，工作的最终目的其实是为了生活，但这其实对于每一个有理想的人来说，都是一个矛盾体。更好的未来意味着你现在必须更加努力的工作，而更加努力的工作又会导致你失去现在的生活，所以，这是一个难题，需要在生活中慢慢体验，在生活中慢慢进步，其实很多时候事情是可以两全其美的，需要的只是我们更加平和的心态和更加细心的生活。

** 																	   :idea:
上周爬山的时候想明白了一个问题，我的这一生到底想要过什么样的生活。我知道这个问题是挺形而上学的。对于这个问题的看法肯定是随着时间不断变化的，但我知道，我必须弄明白我当前阶段想要过什么样的生活，至少，我必须知道，我不想要过什么样的生活。生命的意义不在于很多世俗的东西，你来到这个世界，来体验，来生活，目的是什么，这其实挺难回答的。但依据这样的标准，你可以让自己在做选择的时候变得更容易。其实体验的过程，这种伴随一生的思考的过程的意义，远远大于最终的结果。我穷苦一生，我最终拥有万贯家财，其实这些最终看来都是没有意义的，每一个故事最精彩的地方绝不是结局，而是经过。所以，把握住自己当下的生活， *活在当下* 。

上周以为和驴盆盆吵架，发现了一本好书，叫《非暴力沟通》。发现了我和驴盆盆的沟通的问题在这本书中竟然剖析的那么准确。我一定要 *给我盆盆买一本* 。先人的智慧都在书中，读他们的书可以让我们日行千里，积累经验，所以没事就看看书把，怎么样的生活也比不上读书体验的更多，更快和更深刻。

* 2014-08-17 Sun
** 																	   :work:
这周应该说是接手认证空间以来真正干实事的一周，pete不在，更多的时候需要靠自己去和vida交流。不过还好vida人非常nice，整个交流都显得比较的顺畅。但整个回顾来看，其实做的事情也不是很多，主要是搭建了一个开发环境，一个测试环境和修复了cgi的bug，但因为代码的提交需要codereview，这个事情需要等到vida下周给出独立的代码结构，所以这里还没有进行灰度发布。
此外，本周还上了几次培训课，一个是设计、一个沟通、一个客服，其实都挺有干货的，但吸收不多，还是需要在实际工作中一点一点的积累来的实在，但这些敲门砖对于以后的路会越走越好的，所以这里还是要mark下。

总体来说，感觉自己还是节奏不够快，做事的效率还有待提升。上周有机会观摩了下vida搭建测试环境的速度，才发现自己与别人的生产力差的不是一点半点，路途漫漫，且行且珍惜。其实上周好多时候都卡在了环境的搭建上，这是一条歧路，路没有走好，一开始方向没有走对，因此浪费了很多时间。当接到需求需要修改这个cgi的时候，第一个想法就是直接开始查bug，改代码，改完才发现自己连个环境也没有，然后才去要环境，搭建环境，这时候测试环境和修改代码已经并行了，这样的非耦合导致很多问题就不好处理了。这其实一直以来都是我的问题， *做一件事情的时候，并不能只着眼于结果，必须先看到问题和困难* ，所以吃一堑长一智把，以后在踏入自己不熟悉的领域的时候，要思考，要多问，尽量把多的疑问抛出来，以后可能就会更加好走一些。
此外，沟通也是一个问题，上周的沟通比较多，拉了好多人进行各种各样的权限的开通，总的来说结局不错，但是时间还是稍微有点长，等待的时间太多。大多是因为自己不好意思持续的去打断别人，尤其是电话，因为站在我自己的角度，如果我没有时间回rtx，那么我可能这个时候就在忙着别的什么事情，不希望被乱七八糟的小事打扰，这个对还是不对主要还是要看以后的积累了，以后要是跟人熟了可以在这个方面跟人家聊聊。

其实还是希望能总结出一套属于自己的沟通技巧的。
1. 对症下药：上周上了一门沟通的课程，里面提到了五种类型的人物性格： *老虎型* 、 *孔雀型* 、 *考拉型* 、 *猫头鹰型* 、 *变色龙型* 。老虎型是那种权威不容侵犯的人，孔雀型是那个挺好听的话才会开屏的人，考拉型是非常耐心的人，猫头鹰型是非常精确的人，变色龙就是那种随着环境变化会变化的人。其实懂的了这五种类型的人，相应的在交流的时候就比较容易按类型区别加以对待，产品中很多都是孔雀型的人才，而开发中猫头鹰型的人才会比较多一些。但难就难在如何准确的识别一个人他是哪一类型的。这个就需要多多观察了，有些人很典型，但有些人可能各种各样的性格都有一些，慢慢观察，以后一定可以随心应对的。
2. 广撒网：当需要有很多事情需要沟通的时候，先在rtx打个招呼会比较好，这样优先级不高的事情可能在你处理优先级较高的沟通的时候就被解决了，至少会让人有个心理预期，那样再沟通就会比较方便。
3. 未雨绸缪：当需要用到什么资源的时候，先屡清楚，到了晚上就可以再资源充足的情况下好好开发了，不要等到晚上才发现，找人都找不到。

另外再嘱咐自己一句：工作的目的是为了更好的生活，我在腾讯是为了学到更好的技术，交到更多的朋友，其他的属于你的自然属于你，不属于你的也不用强求，所以面对各种事情的时候，判断的准则是， *我这样做，能让我更快地成长吗？*

** 																	   :home:
本周看完了吴晓波的《激荡三十年》，起因是因为看了qlearning上的吴晓波的讲座，恩，看完书就知道，讲座所有的思想都是来源于他的不段积累，而这些都在他的书籍中都记载，所以想有时间把他全套的书都好好欣赏下。他的一句话这里需要mark下： *三十岁之前不要考虑钱的事，不要着急，不要忧虑* 。
《激荡三十年》主要描述了中国1978年改革开放到2008年的期间中国企业简史，非常有趣，而且其写的故事和我在另外一本外国人写的书《十亿消费者》[fn:1]。读经济学家或者专栏作者的书籍必须带有一定的批判的眼光，因为经济学行业有一句话，叫 *如果我的想法和你一样，那么我就必须另谋职业了* 。但读吴晓波的书很难让你有去批判的感觉，太生动了，生动到你都觉得没有办法去批判。中国的这三十年，也是我成长的三十年，其中很多的事情的发生我都有所耳闻，只可惜没有真正的关注到背后新闻的实质是什么。现在，我又身在整个30年不容遗忘的一个城市，深圳。我懵懂的前20年，必须在以后有所改观，必须以一种更加理性和考究的态度去对待一些事件， *透过现象看本质* ，念了好多年了，却从来没有真正实践过。中国过去的三十年是混乱的三十年，每一次改革都是先从违规开始的。也许这就是整个中国经济的基因。也许再过十年，当前中国的福布斯排行榜中将会发生很大的变化，没有了房地产，经济变革的真正落地，将会彻底改变中国的发展道路，现在中国制造正在从巅峰下滑，也许10年、20年后，技术、创意、服务将领导中国接下去的发展，所有的机会都将不在像现在这样容易，一夜暴富的机会将越来越少，每每想到这个，就有一种去国外看看的冲动。做好技术，淡然面对一切，所有的热门都将不热门，所有的冷门总有一天重新回到人们的视野。
* 2014-08-10 Sun
** 																	   :work:
周一上了一天的课程，入职3年以上的员工们给我们讲了一些关于新人进入tencent的一些建议，主要在工作、生活以及交际上，更多的是如何做好沟通和如何规划好自己的职业发展道路。 *沟通* 是一门学问，这么多年走来，一直都被沟通困扰，不过最近总结出了一条， *站在别人的角度考虑问题，以平常心对待一切* 。这可以使得沟通变得更加的简单和直接。

剩余的工作日主要在写异步的spp，效率感觉挺一般的，完成的情况也不是特别满意。自己近段时间一直在考虑如何更加高效的去做一件事情，  我相信无论是读书还是工作，每件事的内在都存在的一定的统一性，如何已我现有的经验和知识体系，去更加高效的完成任务和解决问题是我应该探索的。其实编程对我来说并不是一件非常容易的事情，毕竟是半路杀出来的，没有经过系统的学习和训练，不过幸运的是，自己对编程还是有兴趣的。人嘛，总要对自己的有清晰的认识，虽然自信是必须的，但现实情况必须要很好的把握，不要不切合实际的去追求，那会死得很惨的。所以，很多时候还是要 *静下心* 来平平静静的做一些事情，一点一滴的积累。

本周算是入职一个月了，peter还特地找我聊了聊，其实发现聊的时候主要说话的还是我，哎，还是担心冷场，所以自己哗啦啦的说个没完，不过感觉自己现在还是挺明白自己的目标的： *强化自己的专业知识，丰富自己的业余视野* 。总体来说这一个月过得还挺不错的，和组里的同事们比较熟，所以也能更加平等的交流，比实习的时候好多了，那时候更多的还是太过于小看自己了。其实，每次交流的时候， *人与人之间的平等性* 对于正常的交流很重要，每次不敢或者不能好好交流，就是要么太高看自己了，要么就是太高看别人了，原因无非这几种。

** 																	   :home:
这几个周末过的其实挺一般的，主要还是感觉心态还是不太好，没有一颗平常心。不过这几个周末，跑步、看书的生活其实挺享受的。或许是因为太着急于钱的事儿了，这真是急不来的事情，准备好自己，该来的总会来的，所以 prepare myself！

** 																	   :idea:
1) 为啥安踏不做智能硬件呢？类似NIKE+这样的东西，屌丝的中国就需要屌丝的NIKE+啊。
2) 众筹开一个阅读空间，按月交钱

* Footnotes

[fn:1] 
感谢驴盆盆


